name: Build

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
    tags:
      - v**

jobs:
  build-docker:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Build Web app
        run: |
          echo "Build Web app"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with: 
          owner: Saturday-Morning-Publishing-LLC
          repo: demo-backend-org
          ref: demo-branch
          github_token: 3c496393274f9ed672afb496f2b5e91ad2cafea7
          workflow_file_name: deploy.yml
          inputs: '{"version":"1.0"}'
      - name: Build Web app
        run: |
          echo "Build Web app"
          sleep 10s

      